#' Get scores based on fixed B-spline basis.
#'
#' Get scores based on fixed B-spline basis in a linear mixed effects model.
#'
#' @param ds Data frame as generated by \code{\link{generateData}}.
#' @param df Number of degrees of freedom to use.
#'
#' @importFrom lme4 lmer ranef
#' @importFrom splines bs
#'
#' @return List containing \code{ds}, a data frame containing the scores, and
#' \code{aic1} and \code{aic2} the AIC values for the mixed effects model for
#' y1 an y2, respectively, to be used for downstream model selection.
#'
#' @export
#'

bSplineScores <- function(ds, df) {
  df <- df - 1
  if (df >= 3) {
    fit1 <- lmer(y1_scaled ~ bs(tt, df = df) + (bs(tt, df = df) | id), data = ds)
    fit2 <- lmer(y2_scaled ~ bs(tt, df = df) + (bs(tt, df = df) | id), data = ds)
  } else {
    fit1 <- lmer(y1_scaled ~ bs(tt, df = df, degree = df) + (bs(tt, df = df, degree = df) | id), data = ds)
    fit2 <- lmer(y2_scaled ~ bs(tt, df = df, degree = df) + (bs(tt, df = df, degree = df) | id), data = ds)
  }
  b1 <- ranef(fit1)$id
  colnames(b1) <- NULL
  b2 <- ranef(fit2)$id
  colnames(b2) <- NULL
  list(ds = data.frame(id = rownames(b1),
                       b1 = b1,
                       b2 = b2),
       aic1 = stats::AIC(fit1),
       aic2 = stats::AIC(fit2))
}
