#' Get scores based on fixed polynomial basis.
#'
#' Get scores based on fixed polynomial basis in a linear mixed effects model.
#' This assumes that ds contains variables labeled \code{tt1}, \code{tt2}, ...,
#' corresponding to polynomial bases of time.
#'
#' @param ds Data frame as generated by \code{\link{generateData}}.
#' @param df Number of degrees of freedom to use.
#'
#' @importFrom lme4 lmer ranef
#' @importFrom stringr str_c
#'
#' @return List containing \code{ds}, a data frame containing the scores, and
#' \code{aic1} and \code{aic2} the AIC values for the mixed effects model for
#' y1 an y2, respectively, to be used for downstream model selection.
#'
#' @export
#'

polynomialScores <- function(ds, df) {
  df <- df - 1
  fm.base <- stringr::str_c('y', 1:2, '_scaled ~ tt')
  fm.re <- stringr::str_c(' + (tt')
  fm.end <- ' | id)'
  if (df > 1) {
    for (j in 2:df) {
      fm.base <- stringr::str_c(fm.base, ' + tt', j)
      fm.re <- stringr::str_c(fm.re, ' + tt', j)
    }
  }
  fm <- stringr::str_c(fm.base, fm.re, fm.end)
  fit1 <- lmer(as.formula(fm[1]), data = ds)
  fit2 <- lmer(as.formula(fm[2]), data = ds)
  b1 <- ranef(fit1)$id
  colnames(b1) <- NULL
  b2 <- ranef(fit2)$id
  colnames(b2) <- NULL
  list(ds = data.frame(id = rownames(b1),
                       b1 = b1,
                       b2 = b2),
       aic1 = stats::AIC(fit1),
       aic2 = stats::AIC(fit2))
}
